JavaリバーシSpringBootプロジェクト: jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController Class Reference
jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController Class Reference
リバーシコントローラークラス
Public Member Functions
ResJson setSetting (HttpServletRequest request)
リバーシ設定反映
ResJson reset (HttpServletRequest request)
リバーシリセット
ResJson reversiPlay (HttpServletRequest request)
リバーシプレイ
FuncsJson ViewMsgDlg (String title, String msg)
メッセージダイアログ
FuncsJson DrawSingle (int y, int x, int sts, int bk, String text)
1マス描画
FuncsJson CurColMsg (String text)
現在の色メッセージ
FuncsJson CurStsMsg (String text)
現在のステータスメッセージ
FuncsJson Wait (int time)
ウェイト
Private Member Functions
ReversiPlay getRvPlay (HttpServletRequest request)
リバーシプレイインスタンス取得
void setRvPlay (HttpServletRequest request, ReversiPlay rvPlay)
リバーシプレイインスタンスセッション保存
Detailed Description
リバーシコントローラークラス
Definition at line 43 of file ReversiController.java.
Member Function Documentation
CurColMsg()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.CurColMsg (String text)
現在の色メッセージ
Parameters
[in] String text テキスト
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Implements jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayInterface.
Definition at line 204 of file ReversiController.java.
CurStsMsg()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.CurStsMsg (String text)
現在のステータスメッセージ
Parameters
[in] String text テキスト
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Implements jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayInterface.
Definition at line 221 of file ReversiController.java.
DrawSingle()
CallbacksJson jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.DrawSingle (int y, int x, int sts, int bk, String text)
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] String text テキスト
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Implements jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayInterface.
Definition at line 183 of file ReversiController.java.
getRvPlay()
ReversiPlay jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.getRvPlay (HttpServletRequest request) private
リバーシプレイインスタンス取得
Parameters
[in] HttpServletRequest request
Returns
ReversiPlay
Author
Yuta Yoshinaga
Date
2020.02.22
Definition at line 116 of file ReversiController.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.setSetting().
reset()
ResJson jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.reset (HttpServletRequest request)
リバーシリセット
Parameters
[in] HttpServletRequest request
Returns
ResJson
Author
Yuta Yoshinaga
Date
2020.02.22
Definition at line 79 of file ReversiController.java.
reversiPlay()
ResJson jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.reversiPlay (HttpServletRequest request)
リバーシプレイ
Parameters
[in] HttpServletRequest request
Returns
ResJson
Author
Yuta Yoshinaga
Date
2020.02.22
Definition at line 97 of file ReversiController.java.
setRvPlay()
void jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.setRvPlay (HttpServletRequest request, ReversiPlay rvPlay) private
リバーシプレイインスタンスセッション保存
Parameters
[in] HttpServletRequest request
[in] ReversiPlay rvPlay
Returns
ありません
Author
Yuta Yoshinaga
Date
2020.02.22
Definition at line 146 of file ReversiController.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.reset(), jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.reversiPlay(), and jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.setSetting().
setSetting()
ResJson jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.setSetting (HttpServletRequest request)
リバーシ設定反映
Parameters
[in] HttpServletRequest request
Returns
ResJson
Author
Yuta Yoshinaga
Date
2020.02.22
Definition at line 58 of file ReversiController.java.
ViewMsgDlg()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.ViewMsgDlg (String title, String msg)
メッセージダイアログ
Parameters
[in] String title タイトル
[in] String msg メッセージ
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Implements jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayInterface.
Definition at line 161 of file ReversiController.java.
Wait()
FuncsJson jp.gr.java_conf.yuta_yoshinaga.reversi.controller.ReversiController.Wait (int time)
ウェイト
Parameters
[in] int time ウェイト時間(msec)
Returns
FuncsJson
Author
Yuta Yoshinaga
Date
2018.04.01
Implements jp.gr.java_conf.yuta_yoshinaga.reversi.model.ReversiPlayInterface.
Definition at line 238 of file ReversiController.java.
The documentation for this class was generated from the following file:
main/java/jp/gr/java_conf/yuta_yoshinaga/reversi/controller/ReversiController.java